[tox]
isolated_build = True
envlist =
    py{310,311,312}-django{42,50,51,52}
    py313-django{51,52}

[testenv]
commands = python -W error::DeprecationWarning -W error::PendingDeprecationWarning manage.py test
deps =
    django42: django>=4.2,<5.0
    django50: django>=5.0,<5.1
    django51: django>=5.1,<5.2
    django52: django>=5.2,<6.0
