# Generated by Django 6.0 on 2025-12-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(max_length=100)),
                ("complete", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
